### ISSUE TITLE
Incompatibility with C heatshrink library 

### ISSUE THREAD

**Issue by ckrenslehner** [huming2207/node-heatshrink#1]
Due to an issue in the crate, your crate relies on, this crate is most likely incompatible with the original implementation of heatshrink (https://github.com/atomicobject/heatshrink).

See https://github.com/snakehand/heatshrink/issues/1

Greetings, Christian

**Comment by huming2207** [comment]
Ohhh thanks for the info. I've bumped the dependencies and now waiting CI to kick in and compile the stuff.

**Comment by ckrenslehner** [comment]
You are welcome :-)

**Comment by huming2207** [comment]
Fixed in v1.1.0
